---
title: "Midterm"
author: "Jack Chen, Emmanuel"
date: "2024-10-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, include=FALSE}
library(tidyverse)
library(sf)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot)
library(dplyr)

root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

palette5 = c("#25CB10", "#5AB60C", "#8FA108",   "#C48C04", "#FA7800")
```

```{r data, include=FALSE}
studentdata = st_read("https://raw.githubusercontent.com/jijinjc/musa-5080-midterm/refs/heads/main/Midterm%20Data/studentData.geo.json") %>%
   st_transform("EPSG:6565")
hospital = st_read("https://raw.githubusercontent.com/jijinjc/musa-5080-midterm/refs/heads/main/Midterm%20Data/DOH_Hospitals202311.geojson") %>% 
  st_transform("EPSG:6565")
farmermarket = st_read("https://raw.githubusercontent.com/jijinjc/musa-5080-midterm/refs/heads/main/Midterm%20Data/Farmers_Markets.geojson") %>%
  st_transform("EPSG:6565")
parks = st_read("https://raw.githubusercontent.com/jijinjc/musa-5080-midterm/refs/heads/main/Midterm%20Data/Parks.geojson") %>%
  st_transform("EPSG:6565")
schools = st_read("https://raw.githubusercontent.com/jijinjc/musa-5080-midterm/refs/heads/main/Midterm%20Data/Schools.geojson") %>%
  st_transform("EPSG:6565")
bikestations = st_read("https://raw.githubusercontent.com/jijinjc/musa-5080-midterm/refs/heads/main/Midterm%20Data/bikestation.geojson") %>%
  st_transform("EPSG:6565")
crime = read.csv("https://raw.githubusercontent.com/jijinjc/musa-5080-midterm/refs/heads/main/Midterm%20Data/incidents_part1_part2.csv")
```

```{r wrangle data, includ=FALSE}
farmersmarket.f = farmermarket %>%
  select(globalid, name, operator, zip, objectid, geometry)
hospital.f = hospital %>%
  select(OBJECTID, GEOCODING_, LONGITUDE, COUNTY, LATITUDE, ZIP_CODE, geometry)
parks.f = parks %>%
  select(OBJECTID, PARK_NAME, DPP_ASSET_ID, geometry)
schools.f = schools %>%
  select(OBJECTID, AUN, SCHOOL_NAME, ZIP_CODE, geometry)
bikestations.f = bikestations %>%
  select(id, name, addressStreet, addressZipCode, latitude, longitude, coordinates, geometry)

studentdata.f = studentdata %>%
  dplyr::select(objectid, basements, geometry, census_tract, category_code, central_air, fireplaces, fuel, garage_type, interior_condition, location, number_of_bedrooms, number_of_bathrooms, number_stories, number_of_rooms, quality_grade, state_code, street_code, sale_price, sale_date, sale_year, total_livable_area, type_heater, total_area, unfinished, unit, view_type, year_built, zip_code, toPredict)
  # mutate(hasBasements = case_when(
  #         !is.na(basements) & basements != 0~ "Y", TRUE~ "N"),
  #       hasAC = case_when(
  #         central_air %in% c("1", "Y") ~ "Y",
  #         TRUE~ "N"),
  #       hasFireplace = case_when(
  #         fireplaces == 0 | is.na(fireplaces)  ~ "N",
  #         TRUE~ "Y"),
  #       hasGarage = case_when(
  #         garage_type == 0 | is.na(garage_type)  ~ "N",
  #         TRUE~ "Y"),
  #       age = 2023 - year_built,
  #       interior_grade = case_when(
  #         interior_condition >= 2 & interior_condition <= 4 ~ "GOOD",
  #         interior_condition > 4 ~ "BAD",
  #         TRUE ~ "NA"),
  #       numRooms = case_when(
  #          is.na(number_of_bedrooms) & !is.na(number_of_bedrooms) ~ number_of_bathrooms,
  #          is.na(number_of_bathrooms) & !is.na(number_of_bedrooms) ~ number_of_bedrooms,
  #          is.na(number_of_bathrooms) & is.na(number_of_bedrooms) ~ 0,
  #          TRUE ~ number_of_bedrooms + number_of_bathrooms),
  #       stories = case_when(
  #          number_stories == 1  ~ "SINGLE",
  #          number_stories == 2  ~ "DOUBLE",
  #          TRUE~ "MULTIPLE"),
  #       area = case_when(
  #          total_livable_area > total_area ~ total_livable_area,
  #          TRUE ~ total_area),
  #       hasHeater = case_when(
  #          type_heater == 0 | is.na(type_heater)  ~ "N",
  #          TRUE~ "Y"),
  #       view = case_when(
  #          view_type == "I" | view_type == "0" | is.na(view_type)   ~ "STANDARD",
  #          view_type == "A" | view_type == "B" | view_type == "C" ~ "GOOD",
  #          TRUE~ "BELOW AVERAGE"),
  #       quality = case_when(
  #          quality_grade %in% c("4", "5", "6", "A", "A+", "A-", "B", "B+","B-","S","S+","X-")  ~ "Good",
  #          TRUE~ "Bad"),
  #       logarea = log(area)) 

modellingdata = studentdata.f %>%
  filter(toPredict == 'MODELLING') %>%
  dplyr::select(-sale_price)

challengedata = studentdata.f %>%
  filter(toPredict == 'CHALLENGE')
```

```{r}
for (k in c(5, 6, 7, 8, 9, 10, 15, 20)) {
  nb_k <- knn2nb(knearneigh(st_coordinates(studentdata.f), k=k))
  wt_k <- nb2listw(nb_k)
  moran_test <- moran.test(studentdata.f$sale_price, wt_k)
  print(paste("Moran's I for k =", k, ":"))
  print(moran_test)
}
```